[build]
builder = "dockerfile"
dockerfilePath = "Backend/project/Dockerfile"
watchPatterns = ["Backend/project/**"]

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
